import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,NavLink,Navigate,Outlet,useLocation,useNavigate} from 'react-router-dom';
import {api,session} from './api';
import {PageHeader,Form} from './ui';
import {Dashboard,Payments,Orders,Tickets} from './operations';
import {Catalog,Menus,Owners} from './setup';
import {EventConfiguration,Features,Memories,Letters} from './event';
import './styles.css';
import {LoginTotoro} from './LoginTotoro';
import './color-refresh.css';
import {NavIcon} from './icons';
const navigation=[['','dashboard','Dashboard','▦','Your event performance and the work that needs your attention.'],['','statistics','Statistics','↗','Approved sales, food tickets, and stall performance.'],['SETUP','stalls','Stalls','▤','Organize the stalls taking part in your event.'],['','foods','Food Catalog','♧','Manage the shared catalog of event foods.'],['','stall-menus','Stall Menus','☷','Connect foods to stalls and manage their selling details.'],['','stall-owners','Stall Owners','♙','Manage the people running each stall.'],['OPERATIONS','orders','Orders','▧','Track customer orders from reservation to completion.'],['','payments','Payment Review','▣','Review payment evidence and keep the queue moving.'],['','tickets','Ticket Redemption','⌗','Verify digital tickets and issue physical food tickets.'],['EVENT CONTROL','event','Event Configuration','⚙','Manage your event schedule and payment settings.'],['','features','Feature Controls','☷','Control the features available during your event.'],['','memories','Memories Feature','▧','Manage the photo window and event memories.'],['','crush-letters','Crush Letters','♡','Review anonymous messages before they appear publicly.']];
function Login({onLogin,user}){const [error,setError]=useState('');if(user)return <Navigate to="/admin/dashboard" replace/>;return <div className="login"><div className="login-brand"><img className="gusto-logo login-logo" src="/gusto-logo.png" alt="Gusto College logo"/><p className="eyebrow">GUSTO EVENT ADMIN</p><h1>Good events start<br/>with a clear view.</h1><p>Your people. Your stalls. Your event.<br/>Everything together in Gusto Fun Fair.</p><LoginTotoro/><small>GUSTO FUN FAIR / 2026</small></div><div className="login-form"><p className="eyebrow">WELCOME TO GUSTO FUN FAIR</p><h2>Sign in to your workspace</h2><p>Use your existing administrator account.</p>{error&&<p role="alert" className="error">{error}</p>}<Form submit="Sign in →" fields={[{key:'name',label:'Account name',required:true,minLength:2,maxLength:50,wide:true},{key:'password',label:'Password',type:'password',required:true,minLength:8,maxLength:128,wide:true}]} onSave={async credentials=>{setError('');const d=await api('/auth/login',{method:'POST',body:credentials});if(d.user.role!=='admin'){session.clear();throw new Error('An administrator account is required.');}session.set(d.token);onLogin(d.user);}}/><small>Access is restricted to authorized event administrators.</small></div></div>;}
function Layout({user,logout}){const location=useLocation(),[open,setOpen]=useState(false);useEffect(()=>setOpen(false),[location.pathname]);const current=navigation.find(n=>location.pathname===`/admin/${n[1]}`);return <div className="app-shell"><header className="top-header"><NavLink to="/admin/dashboard" className="brand"><img className="gusto-logo" src="/gusto-logo.png" alt="Gusto College logo"/><span><strong>Gusto Fun Fair</strong><small>Gusto Event Admin</small></span></NavLink><button className="mobile-menu" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button><div className="header-context">Event administration <span>/</span> {current?.[2]}</div><div className="account"><span className="avatar">{user.name?.slice(0,1).toUpperCase()}</span><div><strong>{user.name}</strong><small>Administrator</small></div><button onClick={logout}>Sign out</button></div></header>{open&&<button className="scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={open?'sidebar open':'sidebar'}><nav aria-label="Admin navigation">{navigation.map(([section,path,title,icon])=><React.Fragment key={path}>{section&&<p className="nav-section">{section}</p>}<NavLink to={`/admin/${path}`}><span className="nav-icon" aria-hidden="true"><NavIcon name={path}/></span>{title}</NavLink></React.Fragment>)}</nav><div className="sidebar-footer"><span className="live-dot"/> Built for a better event<small>Gusto Fun Fair · 2026</small></div></aside><main><PageHeader title={current?.[2]||'Page not found'} description={current?.[4]} action={<span className="workspace-tag">ADMIN WORKSPACE</span>}/><Outlet/><footer className="page-footer">Gusto Fun Fair · Gusto Event Admin<span>All times shown in Myanmar Time</span></footer></main></div>;}
function App(){const [user,setUser]=useState(null),[checking,check]=useState(true),[authError,setAuthError]=useState(''),[retry,setRetry]=useState(0);useEffect(()=>{let active=true;check(true);setAuthError('');if(!session.get()){check(false);return;}api('/auth/me').then(d=>{if(active){if(d.user.role==='admin')setUser(d.user);else session.clear();}}).catch(e=>{if(active&&e.status!==401)setAuthError(e.message);}).finally(()=>active&&check(false));return()=>{active=false;};},[retry]);useEffect(()=>{const clear=()=>setUser(null);window.addEventListener('monitor:unauthorized',clear);return()=>window.removeEventListener('monitor:unauthorized',clear);},[]);if(checking)return <div className="state">Verifying administrator session…</div>;if(authError)return <div className="state error" role="alert"><h1>Unable to verify your session</h1><p>{authError}</p><button onClick={()=>setRetry(x=>x+1)}>Retry</button><button onClick={()=>{session.clear();setAuthError('');setUser(null);}}>Return to sign in</button></div>;return <Routes><Route path="/admin/login" element={<Login user={user} onLogin={setUser}/>}/><Route path="/admin" element={user?<Layout user={user} logout={()=>{session.clear();setUser(null);}}/>:<Navigate to="/admin/login" replace/>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<Dashboard key="dashboard"/>}/><Route path="statistics" element={<Dashboard key="statistics" statistics/>}/><Route path="orders" element={<Orders/>}/><Route path="payments" element={<Payments/>}/><Route path="tickets" element={<Tickets/>}/><Route path="stalls" element={<Catalog key="stalls"/>}/><Route path="foods" element={<Catalog food key="foods"/>}/><Route path="stall-menus" element={<Menus/>}/><Route path="stall-owners" element={<Owners/>}/><Route path="event" element={<EventConfiguration/>}/><Route path="features" element={<Features/>}/><Route path="memories" element={<Memories/>}/><Route path="crush-letters" element={<Letters/>}/><Route path="*" element={<p>Page not found. Choose a page from the navigation.</p>}/></Route><Route path="*" element={<Navigate to="/admin/dashboard" replace/>}/></Routes>;}
createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
