import React, { useEffect, useRef, useState } from 'react';
import { api, id } from './api';
import { BannerMascot } from './BannerMascot';
export function useResource(loader, deps = []) {
  const [state,set] = useState({ loading:true, data:null, error:'' }); const [version, bump] = useState(0);
  useEffect(() => { let active = true; set(s=>({...s,loading:true,error:''})); Promise.resolve().then(loader).then(data=>active&&set({data,loading:false,error:''})).catch(e=>active&&set({data:null,loading:false,error:e.message})); return()=>{active=false;}; }, [...deps,version]);
  return {...state,reload:()=>bump(v=>v+1)};
}
export function State({resource,children}) { if(resource.loading) return <div className="state" role="status"><span className="spinner"/>Loading event data…</div>; if(resource.error) return <div className="state error" role="alert"><h3>Unable to load this page</h3><p>{resource.error}</p><button onClick={resource.reload}>Try again</button></div>; return children(resource.data); }
export function Badge({value}) { return <span className={`badge ${/REJECT|EXPIRE|CANCEL|DISABLED|REUPLOAD/.test(value||'')?'critical':''}`}>{value || '—'}</span>; }
export function Panel({title,action,children,className=''}) {return <section className={`panel ${className}`}><div className="panel-heading"><h2>{title}</h2>{action}</div>{children}</section>;}
export function PageHeader({title,description,action}) {return <div className="page-heading"><div><p className="eyebrow">GUSTO FUN FAIR / ADMINISTRATION</p><h1>{title}</h1><p>{description}</p></div><BannerMascot/>{action}</div>;}
export function Table({columns,rows,empty='No records to show.',pageSize=10}) {
  const [page,setPage]=useState(1); useEffect(()=>setPage(1),[rows]); const pages=Math.max(1,Math.ceil(rows.length/pageSize));
  return !rows.length?<div className="state"><span className="empty-icon">⌑</span><h3>{empty}</h3><p>Records will appear here when they are available.</p></div>:<><div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c.label}>{c.label}</th>)}</tr></thead><tbody>{rows.slice((page-1)*pageSize,page*pageSize).map((row,i)=><tr key={id(row)||i}>{columns.map(c=><td key={c.label}>{c.render?c.render(row):row[c.key]??'—'}</td>)}</tr>)}</tbody></table></div>{rows.length>pageSize&&<div className="pagination"><span>{rows.length} records · Page {page} of {pages}</span><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button></div>}</>;
}
export function Toolbar({search,setSearch,filter,setFilter,options=[],placeholder='Search records…'}) {return <div className="toolbar"><input aria-label="Search records" type="search" placeholder={placeholder} value={search} onChange={e=>setSearch(e.target.value)}/>{setFilter&&<select aria-label="Filter records" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{options.map(o=><option key={o}>{o}</option>)}</select>}</div>;}
export function Modal({title,onClose,children}) {
  const ref=useRef(); useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus();},[]);
  return <dialog ref={ref} onCancel={e=>{e.preventDefault();onClose();}}><header><h2>{title}</h2><button aria-label="Close dialog" className="icon-button" onClick={onClose}>×</button></header><div className="modal-body">{children}</div></dialog>;
}
function FileField({field,value,onChange}) {
  const [preview,setPreview]=useState(field.preview||'');
  useEffect(()=>{if(!value)return;const url=URL.createObjectURL(value);setPreview(url);return()=>URL.revokeObjectURL(url);},[value]);
  return <span className="file-field">{preview&&<img src={preview} alt=""/>}<input aria-label={field.label} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>onChange(e.target.files[0]||null)}/></span>;
}
export function Form({fields,initial={},onSave,submit='Save changes',confirmation}) {
  const [values,set]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
  async function save(e){e.preventDefault();if(confirmation&&!window.confirm(confirmation))return;setBusy(true);setError('');setSuccess('');try{await onSave(values);setSuccess('Changes saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <form onSubmit={save} className="form-grid">{fields.map(f=><label key={f.key} className={f.wide?'wide':''}><span>{f.label}</span>{f.type==='checkbox'?<input aria-label={f.label} type="checkbox" checked={!!values[f.key]} onChange={e=>set({...values,[f.key]:e.target.checked})}/>:f.type==='file'?<FileField field={f} value={values[f.key]} onChange={file=>set({...values,[f.key]:file})}/>:f.options?<select aria-label={f.label} required={f.required} value={values[f.key]??''} onChange={e=>set({...values,[f.key]:e.target.value})}><option value="">Select…</option>{f.options.map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select>:f.type==='textarea'?<textarea aria-label={f.label} maxLength={f.maxLength||500} value={values[f.key]??''} onChange={e=>set({...values,[f.key]:e.target.value})}/>:<input aria-label={f.label} type={f.type||'text'} required={f.required} min={f.min} max={f.max} step={f.step} minLength={f.minLength} maxLength={f.maxLength} autoComplete={f.type==='password'?'new-password':undefined} value={values[f.key]??''} onChange={e=>set({...values,[f.key]:f.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value})}/ >}{f.help&&<small>{f.help}</small>}</label>)}{error&&<p className="error wide" role="alert">{error}</p>}{success&&<p className="notice wide" role="status">{success}</p>}<div className="wide form-actions"><button className="primary" disabled={busy}>{busy?'Saving…':submit}</button></div></form>;
}
export function Action({children,onAction,confirm,className=''}) {const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);return <><button className={className} disabled={busy} onClick={async()=>{if(confirm&&!window.confirm(confirm))return;setBusy(true);setError('');try{await onAction();setDone(true);}catch(e){setError(e.message);}finally{setBusy(false);}}}>{busy?'Working…':children}</button>{error&&<span className="error" role="alert">{error}</span>}{done&&<span className="sr-only" role="status">Action completed successfully.</span>}</>;}
export function Proof({payment}) {const r=useResource(async()=>{const proof=payment.proofs?.find(p=>p.version===payment.proofVersion);if(!proof)throw new Error('No current payment proof available.');return api(proof.imageUrl.replace(/^\/api/,''),{blob:true});},[payment.id,payment.proofVersion]);const [url,setUrl]=useState('');useEffect(()=>{if(!r.data)return;const u=URL.createObjectURL(r.data);setUrl(u);return()=>URL.revokeObjectURL(u);},[r.data]);return <State resource={r}>{()=>url&&<a href={url} target="_blank" rel="noreferrer"><img className="proof" src={url} alt={`Payment proof version ${payment.proofVersion}; open full size`}/></a>}</State>;}
