import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const config=JSON.parse(readFileSync(new URL('../../data/monitor-local/configuration.json',import.meta.url),'utf8'));
async function login(page){await page.goto('/admin/login');await page.getByLabel('Account name',{exact:true}).fill(config.adminName);await page.getByLabel('Password',{exact:true}).fill(config.adminPassword);await page.getByRole('button',{name:'Sign in →'}).click();await expect(page.getByRole('heading',{level:1,name:'Dashboard'})).toBeVisible();await expect(page.getByText('Loading event data…')).toHaveCount(0);}
async function api(page,path,method='GET',data,token){token??=await page.evaluate(()=>sessionStorage.getItem('monitor.token'));const res=await page.request.fetch(`/api${path}`,{method,headers:{Authorization:`Bearer ${token}`},...(data!==undefined?{data}:{})});expect(res.ok(),`${method} ${path}: ${res.status()} ${res.ok()?'':await res.text()}`).toBeTruthy();return res.status()===204?{}:res.json();}
test('real login, all admin pages, and refreshed session use the existing backend',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await login(page);
 await page.screenshot({path:'test-results/live-dashboard.png',fullPage:true});
 for(const title of ['Statistics','Stalls','Food Catalog','Stall Menus','Stall Owners','Orders','Payment Review','Ticket Redemption','Event Configuration','Feature Controls','Memories Feature','Crush Letters','Dashboard']){
  await page.getByRole('navigation').getByRole('link',{name:title,exact:true}).click();await expect(page.getByRole('heading',{level:1,name:title,exact:true})).toBeVisible();await expect(page.getByText('Loading event data…')).toHaveCount(0);await expect(page.getByRole('alert')).toHaveCount(0);
 }
 await page.reload();await expect(page.getByRole('heading',{level:1,name:'Dashboard'})).toBeVisible();await expect(page.getByText('Loading event data…')).toHaveCount(0);expect(errors).toEqual([]);
});
test('real catalog, menu pricing, owner creation, and access changes persist',async({page})=>{
 await login(page);page.on('dialog',d=>d.accept());const suffix=Date.now().toString(36),stallName=`TEST Stall ${suffix}`,foodName=`TEST Food ${suffix}`;let stall,food;
 try{
 await page.goto('/admin/stalls');await page.getByRole('button',{name:'Add stall'}).click();await page.getByLabel('Stall name',{exact:true}).fill(stallName);await page.getByLabel('Batch',{exact:true}).fill('Local test');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByText('Stall saved.')).toBeVisible();stall=(await api(page,'/admin/stalls')).stalls.find(s=>s.stallName===stallName);expect(stall).toBeTruthy();
 await page.goto('/admin/foods');await page.getByRole('button',{name:'Add food'}).click();await page.getByLabel('Food name',{exact:true}).fill(foodName);await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByText('Food saved.')).toBeVisible();food=(await api(page,'/admin/foods')).foods.find(f=>f.name===foodName);expect(food).toBeTruthy();
 await page.goto('/admin/stall-menus');await page.getByRole('button',{name:'Add food to stall'}).click();await page.getByLabel('Stall',{exact:true}).selectOption(stall._id);await page.getByLabel('Food',{exact:true}).selectOption(food._id);await page.getByLabel('Event-day price (MMK)').fill('3000');await page.getByLabel('Ticket limit',{exact:true}).fill('20');await page.getByLabel('Discount value',{exact:true}).fill('10');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByText('Menu entry saved.')).toBeVisible();const entry=(await api(page,`/admin/stall-foods?stallId=${stall._id}`)).stallFoods[0];expect(entry.preorderPrice).toBe(2700);expect(entry.ticketsRemaining).toBe(20);
 await page.goto('/admin/stall-owners');await page.getByRole('searchbox').fill(stallName);await page.getByRole('button',{name:'Create owner'}).click();await page.getByLabel('Name / login name').fill(`TEST Owner ${suffix}`);await page.getByLabel('New password').fill(`LocalOwner-${suffix}-only`);await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByText('Owner account saved.')).toBeVisible();await page.getByRole('button',{name:'Disable access'}).click();await expect(page.getByText('Owner access updated.')).toBeVisible();expect((await api(page,`/admin/stalls/${stall._id}/owner`)).owner.isActive).toBe(false);
 }finally{if(stall)await api(page,`/admin/stalls/${stall._id}/status`,'PATCH',{isActive:false});if(food)await api(page,`/admin/foods/${food._id}`,'PATCH',{isActive:false});}
});
test('real event switches and letter moderation use existing APIs',async({page})=>{
 await login(page);page.on('dialog',d=>d.accept());const {event}=await api(page,'/admin/event');const recipient=`TEST Recipient ${Date.now()}`;
 try{
  await page.goto('/admin/features');const row=page.locator('.feature-row').filter({has:page.getByRole('heading',{name:'Crush Letters',exact:true})});if(!event.featureFlags.crushLettersEnabled)await row.getByRole('button',{name:'Turn on'}).click();await expect(row.getByText('ENABLED',{exact:true})).toBeVisible();
  await api(page,'/crush-letters','POST',{recipientName:recipient,message:'Local integration check — thank you for helping at the event.'});await page.goto('/admin/crush-letters');const letterRow=page.getByRole('row').filter({hasText:recipient});await letterRow.getByRole('button',{name:'Approve',exact:true}).click();await expect(page.getByText('Letter approved.')).toBeVisible();const approved=await api(page,'/admin/crush-letters?status=APPROVED&limit=50');expect(approved.crushLetters.some(l=>l.recipientName===recipient)).toBe(true);
  const letter=approved.crushLetters.find(l=>l.recipientName===recipient);await api(page,`/admin/crush-letters/${letter.id}/visibility`,'PATCH',{hidden:true});
  await page.goto('/admin/event');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByText('Changes saved.')).toBeVisible();const saved=(await api(page,'/admin/event')).event;expect(new Date(saved.preorderOpenAt).toISOString()).toBe(new Date(event.preorderOpenAt).toISOString());
 }finally{await api(page,'/admin/event','PATCH',{featureFlags:{crushLettersEnabled:event.featureFlags.crushLettersEnabled}});}
});
test('customer order appears in admin and server rejects non-admin access',async({page})=>{
 await login(page);const customer=await api(page,'/auth/register','POST',{name:`TEST Buyer ${Date.now()}`,password:`LocalTest-${Date.now()}`});const denied=await page.request.get('/api/admin/dashboard',{headers:{Authorization:`Bearer ${customer.token}`}});expect(denied.status()).toBe(403);
 const {foods}=await api(page,'/foods');const food=foods.find(f=>f.ticketsRemaining>0);expect(food).toBeTruthy();const created=await api(page,'/orders','POST',{items:[{stallFoodId:food.stallFoodId,quantity:1}]},customer.token);const order=created.order;expect(order).toBeTruthy();
 try{await page.goto('/admin/orders');await page.getByRole('searchbox').fill(order.paymentReference);await page.getByRole('button',{name:'View order'}).click();await expect(page.getByRole('dialog')).toContainText(order.paymentReference);await expect(page.getByRole('dialog')).toContainText('RESERVED');}finally{await api(page,`/orders/${order._id}/cancel`,'POST',undefined,customer.token);}
});
