import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import env from './config/env.js';
import adminRoutes from './routes/adminRoutes.js';
import authRoutes from './routes/authRoutes.js';
import foodRoutes from './routes/foodRoutes.js';
import eventRoutes from './routes/eventRoutes.js';
import memoryRoutes from './routes/memoryRoutes.js';
import orderRoutes from './routes/orderRoutes.js';
import paymentRoutes from './routes/paymentRoutes.js';
import stallRoutes from './routes/stallRoutes.js';
import ticketRoutes from './routes/ticketRoutes.js';
import { errorHandler } from './middleware/errorMiddleware.js';
import { notFound } from './middleware/notFoundMiddleware.js';

const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: env.clientUrl, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.get('/api/health', (_req, res) => res.json({ status: 'ok', message: 'Fun Fair API is running' }));
app.use('/api/event', eventRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/stalls', stallRoutes);
app.use('/api/foods', foodRoutes);
app.use('/api/orders', orderRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/tickets', ticketRoutes);
app.use('/api/memories', memoryRoutes);
app.use('/api/admin', adminRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
